export const demoCredentials = {
  admin: {
    name: 'Administrator',
    email: 'admin@example.com',
    password: 'password123',
    role: 'admin',
    phone: '+91 98765 43210',
  },
  doctor: {
    name: 'Dr. Rajesh Sharma',
    email: 'doctor@example.com',
    password: 'password123',
    role: 'doctor',
    phone: '+91 98765 11223',
    specialization: 'General Physician',
    qualification: 'MBBS, MD (Internal Medicine)',
    experience: 12,
    hospital: 'Sitapur District Community Hospital',
    location: 'Sitapur District, UP',
    consultationFee: 0,
    about: 'Dedicated rural medicine specialist with over 12 years of experience providing primary and preventive care in underserved rural communities.',
    profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
  },
  patient: {
    name: 'Ramesh Patel',
    email: 'patient@example.com',
    password: 'password123',
    role: 'patient',
    phone: '+91 98765 88990',
    age: 38,
    gender: 'Male',
    location: 'Kheri Village, Lakhimpur',
    bloodGroup: 'B+',
    emergencyContact: '+91 98765 88991',
  },
};

export const sampleDoctors = [
  {
    name: 'Dr. Priya Nair',
    email: 'priya.nair@example.com',
    phone: '+91 98765 22334',
    specialization: 'Cardiologist',
    qualification: 'MBBS, MD, DM (Cardiology)',
    experience: 14,
    hospital: 'Sonbhadra Tribal Health Mission Hospital',
    location: 'Sonbhadra, UP',
    consultationFee: 50,
    about: 'Experienced cardiologist focusing on rural cardiovascular screening, hypertension management, and non-invasive cardiac care.',
    profileImage: 'https://images.unsplash.com/photo-1594824813689-537a4e69b2d8?w=400&auto=format&fit=crop&q=80',
    rating: 4.9,
  },
  {
    name: 'Dr. Amit Verma',
    email: 'amit.verma@example.com',
    phone: '+91 98765 33445',
    specialization: 'Dermatologist',
    qualification: 'MBBS, MD (Dermatology & Venereology)',
    experience: 9,
    hospital: 'Navjeevan Community Clinic',
    location: 'Hardoi Rural District, UP',
    consultationFee: 0,
    about: 'Expert in treating infectious skin diseases, rural dermatoses, allergies, and pediatric skin conditions common in farming communities.',
    profileImage: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    rating: 4.7,
  },
  {
    name: 'Dr. Sunita Kulkarni',
    email: 'sunita.kulkarni@example.com',
    phone: '+91 98765 44556',
    specialization: 'Pediatrician',
    qualification: 'MBBS, DCH, MD (Pediatrics)',
    experience: 11,
    hospital: 'Barabanki Community Healthcare Centre',
    location: 'Barabanki District, UP',
    consultationFee: 0,
    about: 'Passionate child specialist dedicated to neonatal care, malnutrition eradication, immunization drives, and child development in rural areas.',
    profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    rating: 5.0,
  },
  {
    name: 'Dr. Ananya Mukherjee',
    email: 'ananya.m@example.com',
    phone: '+91 98765 55667',
    specialization: 'Gynecologist',
    qualification: 'MBBS, MS (Obstetrics & Gynecology), DGO',
    experience: 15,
    hospital: 'Janani Matritva Rural Health Centre',
    location: 'Raebareli Outskirts, UP',
    consultationFee: 0,
    about: 'Advocate for maternal health and safe childbirth in remote areas. Conducts regular antenatal checkups and high-risk pregnancy management.',
    profileImage: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&auto=format&fit=crop&q=80',
    rating: 4.9,
  },
  {
    name: 'Dr. Vikram Rathore',
    email: 'vikram.rathore@example.com',
    phone: '+91 98765 66778',
    specialization: 'Orthopedic',
    qualification: 'MBBS, MS (Orthopedics), Fellowship Joint Surgery',
    experience: 10,
    hospital: 'Mirzapur Grameen Hospital',
    location: 'Mirzapur, UP',
    consultationFee: 40,
    about: 'Specializes in rural trauma care, bone fractures from agricultural work, arthritis management, and spine health education.',
    profileImage: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=400&auto=format&fit=crop&q=80',
    rating: 4.8,
  },
  {
    name: 'Dr. Neha Saxena',
    email: 'neha.saxena@example.com',
    phone: '+91 98765 77889',
    specialization: 'ENT Specialist',
    qualification: 'MBBS, MS (Otorhinolaryngology)',
    experience: 8,
    hospital: 'Asha Rural Head & Neck Clinic',
    location: 'Unnao Rural, UP',
    consultationFee: 0,
    about: 'ENT surgeon conducting hearing screenings, ear infections management, and throat disorder treatments for rural school children and adults.',
    profileImage: 'https://images.unsplash.com/photo-1594824813606-d08310f8be78?w=400&auto=format&fit=crop&q=80',
    rating: 4.6,
  },
  {
    name: 'Dr. Farhan Ali',
    email: 'farhan.ali@example.com',
    phone: '+91 98765 88991',
    specialization: 'Dentist',
    qualification: 'BDS, MDS (Oral & Maxillofacial Surgery)',
    experience: 9,
    hospital: 'Sanjeevani Dental Care Outreach',
    location: 'Fatehpur District, UP',
    consultationFee: 20,
    about: 'Provides preventative oral health care, extractions, root canals, and community education against tobacco-induced oral lesions.',
    profileImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=400&auto=format&fit=crop&q=80',
    rating: 4.7,
  },
  {
    name: 'Dr. Arvind Swaminathan',
    email: 'arvind.s@example.com',
    phone: '+91 98765 99002',
    specialization: 'Ophthalmologist',
    qualification: 'MBBS, MS (Ophthalmology)',
    experience: 13,
    hospital: 'Drishti Rural Eye Mission',
    location: 'Gonda Sector 5, UP',
    consultationFee: 0,
    about: 'Dedicated eye specialist performing cataract surgeries, glaucoma screening, and distributing corrective spectacles in remote villages.',
    profileImage: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80',
    rating: 4.9,
  },
  {
    name: 'Dr. Meera Deshmukh',
    email: 'meera.deshmukh@example.com',
    phone: '+91 98765 00112',
    specialization: 'General Physician',
    qualification: 'MBBS, Fellowship Family Medicine',
    experience: 7,
    hospital: 'Lakhimpur Rural Health Sanatorium',
    location: 'Lakhimpur Block III, UP',
    consultationFee: 0,
    about: 'Community physician managing endemic infectious illnesses, waterborne disease prevention, and diabetes monitoring in rural settlements.',
    profileImage: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&auto=format&fit=crop&q=80',
    rating: 4.8,
  },
];

export const samplePatients = [
  {
    name: 'Sunita Devi',
    email: 'sunita.devi@example.com',
    phone: '+91 98111 22334',
    age: 45,
    gender: 'Female',
    location: 'Bilhaur Village, Kanpur Dehat',
    bloodGroup: 'B+',
    emergencyContact: '+91 98111 22335',
  },
  {
    name: 'Mohammad Tariq',
    email: 'tariq.m@example.com',
    phone: '+91 98222 33445',
    age: 29,
    gender: 'Male',
    location: 'Mohanlalganj Rural, Lucknow',
    bloodGroup: 'O+',
    emergencyContact: '+91 98222 33446',
  },
  {
    name: 'Kavita Bai',
    email: 'kavita.bai@example.com',
    phone: '+91 98333 44556',
    age: 52,
    gender: 'Female',
    location: 'Gauri Bazar, Deoria',
    bloodGroup: 'A+',
    emergencyContact: '+91 98333 44557',
  },
  {
    name: 'Harpreet Singh',
    email: 'harpreet.s@example.com',
    phone: '+91 98444 55667',
    age: 34,
    gender: 'Male',
    location: 'Puranpur Tehsil, Pilibhit',
    bloodGroup: 'AB+',
    emergencyContact: '+91 98444 55668',
  },
];

export const sampleHospitals = [
  {
    name: 'Sitapur District Community Hospital',
    location: 'Sitapur Rural Highway, UP',
    contact: '+91 5862-245100',
    totalBeds: 120,
    availableBeds: 38,
    type: 'Sub-District Hospital',
    emergencyServices: true,
    facilities: ['24x7 Emergency ICU', 'Maternity Ward', 'Telemedicine Outreach', 'Diagnostic Lab'],
  },
  {
    name: 'Sonbhadra Tribal Health Mission Hospital',
    location: 'Sonbhadra Hills Zone 4, UP',
    contact: '+91 5444-220199',
    totalBeds: 75,
    availableBeds: 22,
    type: 'Tribal Healthcare Hub',
    emergencyServices: true,
    facilities: ['Trauma Center', 'Blood Storage Facility', 'Malaria & Vector Unit', 'Cardiac Monitor'],
  },
  {
    name: 'Lakhimpur Rural Health Sanatorium',
    location: 'Kheri Block II, Lakhimpur, UP',
    contact: '+91 5872-251400',
    totalBeds: 90,
    availableBeds: 41,
    type: 'Community Health Centre',
    emergencyServices: true,
    facilities: ['General Inpatient Ward', 'Pediatric Clinic', 'Mobile Medical Unit', 'Free Pharmacy'],
  },
  {
    name: 'Barabanki Community Healthcare Centre',
    location: 'Dewa Road, Barabanki, UP',
    contact: '+91 5248-223400',
    totalBeds: 60,
    availableBeds: 15,
    type: 'Primary Healthcare Centre',
    emergencyServices: true,
    facilities: ['24x7 Ambulance Hub', 'Antenatal Care Unit', 'Vaccine Cold Storage'],
  },
  {
    name: 'Mirzapur Grameen Hospital',
    location: 'Vindhya Valley Sector 3, Mirzapur, UP',
    contact: '+91 5442-261200',
    totalBeds: 80,
    availableBeds: 29,
    type: 'Rural Referral Center',
    emergencyServices: true,
    facilities: ['Orthopedic Trauma Unit', 'Digital X-Ray', 'Minor OT', 'Physiotherapy Center'],
  },
];

export const sampleDoctorSchedule = [
  { day: 'Monday', slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  { day: 'Tuesday', slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  { day: 'Wednesday', slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  { day: 'Thursday', slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  { day: 'Friday', slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  { day: 'Saturday', slots: ['09:00 AM', '10:00 AM', '11:30 AM', '01:00 PM'] },
];
